name: Create Plugins

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: buildbase.bat
        run: buildbase.bat ..\vs2022\libsodium.sln 17
        working-directory: libsodium/builds/msvc/build/
        shell: cmd
      - uses: actions/upload-artifact@v3
        with:
          name: build-win-x64
          path: libsodium/bin/x64/Release/v143/dynamic/libsodium.dll
      - uses: actions/upload-artifact@v3
        with:
          name: build-win-x86
          path: libsodium/bin/Win32/Release/v143/dynamic/libsodium.dll

  build-windows-arm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@d866436887ad1b24590684f9d00480376663dd36
        with:
          version: 0.11.0
      - name: build
        run: |
          zig build -Doptimize=ReleaseFast -Dtarget=aarch64-windows
        working-directory: libsodium
      - name: tests
        run: cd zig-out/bin && ./run.sh
        working-directory: libsodium
      - uses: actions/upload-artifact@v3
        with:
          name: build-win-aarch64
          path: libsodium/zig-out/lib/sodium_shared.dll

  build-linux-glibc:
    runs-on: ubuntu-latest
    steps:
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@d866436887ad1b24590684f9d00480376663dd36
        with:
          version: 0.11.0
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        run: |
          zig build -Doptimize=ReleaseFast -Dtarget=x86_64-linux-gnu.2.17 -Dcpu=sandybridge
        working-directory: libsodium
      - name: tests
        run: cd zig-out/bin && ./run.sh
        working-directory: libsodium
      - uses: actions/upload-artifact@v3
        with:
          name: build-linux-x64
          path: libsodium/zig-out/lib/libsodium.so

  build-macos-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: configure
        run: env CFLAGS="-Ofast -arch x86_64 -mmacosx-version-min=10.15" LDFLAGS="-arch x86_64 -mmacosx-version-min=10.15" ./configure --host=arm-apple-darwin20 --prefix=$PWD/.libsodium-build
        working-directory: libsodium
      - name: make
        run: make
        working-directory: libsodium
      - name: make check
        run: make check
        working-directory: libsodium
      - name: make install
        run: make install
        working-directory: libsodium
      - uses: actions/upload-artifact@v3
        with:
          name: build-osx-x64
          path: libsodium/.libsodium-build/lib/libsodium.dylib

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: configure
        run: env CFLAGS="-Ofast -arch arm64 -mmacosx-version-min=10.15" LDFLAGS="-arch arm64 -mmacosx-version-min=10.15" ./configure --host=arm-apple-darwin20 --prefix=$PWD/.libsodium-build
        working-directory: libsodium
      - name: make
        run: make
        working-directory: libsodium
      - name: make install
        run: make install
        working-directory: libsodium
      - uses: actions/upload-artifact@v3
        with:
          name: build-osx-arm64
          path: libsodium/.libsodium-build/lib/libsodium.dylib
  
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update packages list
        run: sudo apt-get update
      - name: Install base dependencies
        run: sudo apt-get install -y libtool autoconf automake unzip
      - name: Install Android NDK
        run: |
          mkdir /tmp/android && cd /tmp/android
          curl -o ndk.zip -L https://dl.google.com/android/repository/android-ndk-r26c-linux.zip
          unzip ndk.zip && rm -f *.zip && mv android-ndk* ndk
      - name: Android compilation
        run: |
          env ANDROID_NDK_HOME=/tmp/android/ndk ./dist-build/android-aar.sh
        working-directory: libsodium
      - uses: actions/upload-artifact@v3
        with:
          name: build-android-aar
          path: libsodium/libsodium-*.aar
