name: Create Plugins

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [macos-latest]
        platform: [android-armv7, android-arm64, macos, ios, win32, win64]
        include:
          - host: ubuntu-latest
            platform: linux64
          - host: ubuntu-latest
            platform: linux32

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Build Deps
        run: |
          packages='libtool autoconf automake wget'
          brew update
          for pkg in libtool autoconf automake wget; do
            if brew list -1 | grep -q "^${pkg}\&"; then
              echo "Package '$pkg' is installed"
            else
              echo "Package '$pkg' is not installed"
              brew install $pkg
            fi
          done
          brew upgrade ${packages} || true

      - name: Setup Libsodium for development
        run: |
          cd libsodium
          ./autogen.sh -s

      - name: Build ${{ matrix.platform }}
        run: ./build_scripts/${{ matrix.platform }}.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}
          path: output/builds
